package com.monopolynew.enums;

public enum GameStage {
    TURN_START,
    JAIL_RELEASE_START,
    ROLLED_FOR_TURN,
    ROLLED_FOR_JAIL,
    AWAITING_PAYMENT,
    AWAITING_JAIL_FINE,
    BUY_PROPOSAL,
    AUCTION_IN_PROGRESS,
    AWAITING_AUCTION_RAISE,
    AWAITING_AUCTION_BUY,
    DEAL_OFFER
}