export const GameStages: Record<string, string> = {
  TURN_START: 'TURN_START',
  JAIL_RELEASE_START: 'JAIL_RELEASE_START',
  ROLLED_FOR_TURN: 'ROLLED_FOR_TURN',
  ROLLED_FOR_JAIL: 'ROLLED_FOR_JAIL',
  AWAITING_PAYMENT: 'AWAITING_PAYMENT',
  AWAITING_JAIL_FINE: 'AWAITING_JAIL_FINE',
  BUY_PROPOSAL: 'BUY_PROPOSAL',
  AUCTION_IN_PROGRESS: 'AUCTION_IN_PROGRESS',
  AWAITING_AUCTION_RAISE: 'AWAITING_AUCTION_RAISE',
  AWAITING_AUCTION_BUY: 'AWAITING_AUCTION_BUY',
  DEAL_OFFER: 'DEAL_OFFER',
}
