name: Fast tests

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      repo-name:
        required: false
        default: ${{ github.event.repository.name }}
        type: string
  
jobs:
  run-uts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Run mvn command
        run: maven clean test
      - name: Get job_id
        uses: Tiryoh/gha-jobid-action@v0
        id: ids
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: run-uts
      - name: Test execution time summary
        shell: pwsh
        run: |
          $testStep = (curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/andrew-s-titov/${{ inputs.repo-name }}/actions/jobs/${{ steps.ids.outputs.job_id }} | ConvertFrom-Json).steps[2]
          $durationSec =  (NEW-TIMESPAN -Start $testStep.started_at -End $testStep.completed_at).TotalSeconds
          if ($durationSec -gt 120) {
            Write-Output "WARNING: build and UTs took more that 2 minutes: ($durationSec) seconds in total"
          } else {
            Write-Output "Build and UTs took $durationSec seconds"
          }
